import { Variable } from "../types";

export const fontWeightVariables: Variable[] = [
  {
    key: "--font-weight-thin",
    value: "100",
    name: "Font Weight Thin",
    category: "font-weight",
    equivalent: "100",
    documentationUrl: "",
  },
  {
    key: "--font-weight-extralight",
    value: "200",
    name: "Font Weight Extralight",
    category: "font-weight",
    equivalent: "200",
    documentationUrl: "",
  },
  {
    key: "--font-weight-light",
    value: "300",
    name: "Font Weight Light",
    category: "font-weight",
    equivalent: "300",
    documentationUrl: "",
  },
  {
    key: "--font-weight-normal",
    value: "400",
    name: "Font Weight Normal",
    category: "font-weight",
    equivalent: "400",
    documentationUrl: "",
  },
  {
    key: "--font-weight-medium",
    value: "500",
    name: "Font Weight medium",
    category: "font-weight",
    equivalent: "500",
    documentationUrl: "",
  },
  {
    key: "--font-weight-semibold",
    value: "600",
    name: "Font Weight Semibold",
    category: "font-weight",
    equivalent: "600",
    documentationUrl: "",
  },
  {
    key: "--font-weight-bold",
    value: "700",
    name: "Font Weight Bold",
    category: "font-weight",
    equivalent: "700",
    documentationUrl: "",
  },
  {
    key: "--font-weight-extrabold",
    value: "800",
    name: "Font Weight Extrabold",
    category: "font-weight",
    equivalent: "800",
    documentationUrl: "",
  },
  {
    key: "--font-weight-black",
    value: "900",
    name: "Font Weight Black",
    category: "font-weight",
    equivalent: "900",
    documentationUrl: "",
  },
];
