import { Variable } from "../types";

export const sizeVariables: Variable[] = [
  {
    key: "--s-0",
    value: "0px",
    name: "Size 0",
    category: "size",
    equivalent: "0px",
    documentationUrl: "",
  },
  {
    key: "--s-px",
    value: "1px",
    name: "Size 1px",
    category: "size",
    equivalent: "1px",
    documentationUrl: "",
  },
  {
    key: "--s-0-5",
    value: "0.125rem",
    name: "Size 0.5",
    category: "size",
    equivalent: "2px",
    documentationUrl: "",
  },
  {
    key: "--s-1",
    value: "0.25rem",
    name: "Size 1",
    category: "size",
    equivalent: "4px",
    documentationUrl: "",
  },
  {
    key: "--s-1-5",
    value: "0.375rem",
    name: "Size 1.5",
    category: "size",
    equivalent: "6px",
    documentationUrl: "",
  },
  {
    key: "--s-2",
    value: "0.5rem",
    name: "Size 2",
    category: "size",
    equivalent: "8px",
    documentationUrl: "",
  },
  {
    key: "--s-2-5",
    value: "0.625rem",
    name: "Size 2.5",
    category: "size",
    equivalent: "10px",
    documentationUrl: "",
  },
  {
    key: "--s-3",
    value: "0.75rem",
    name: "Size 3",
    category: "size",
    equivalent: "12px",
    documentationUrl: "",
  },
  {
    key: "--s-3-5",
    value: "0.875rem",
    name: "Size 3.5",
    category: "size",
    equivalent: "14px",
    documentationUrl: "",
  },
  {
    key: "--s-4",
    value: "1rem",
    name: "Size 4",
    category: "size",
    equivalent: "16px",
    documentationUrl: "",
  },
  {
    key: "--s-5",
    value: "1.25rem",
    name: "Size 5",
    category: "size",
    equivalent: "20px",
    documentationUrl: "",
  },
  {
    key: "--s-6",
    value: "1.5rem",
    name: "Size 6",
    category: "size",
    equivalent: "24px",
    documentationUrl: "",
  },
  {
    key: "--s-7",
    value: "1.75rem",
    name: "Size 7",
    category: "size",
    equivalent: "28px",
    documentationUrl: "",
  },
  {
    key: "--s-8",
    value: "2rem",
    name: "Size 8",
    category: "size",
    equivalent: "32px",
    documentationUrl: "",
  },
  {
    key: "--s-9",
    value: "2.25rem",
    name: "Size 9",
    category: "size",
    equivalent: "36px",
    documentationUrl: "",
  },
  {
    key: "--s-10",
    value: "2.5rem",
    name: "Size 10",
    category: "size",
    equivalent: "40px",
    documentationUrl: "",
  },
  {
    key: "--s-11",
    value: "2.75rem",
    name: "Size 11",
    category: "size",
    equivalent: "44px",
    documentationUrl: "",
  },
  {
    key: "--s-12",
    value: "3rem",
    name: "Size 12",
    category: "size",
    equivalent: "48px",
    documentationUrl: "",
  },
  {
    key: "--s-14",
    value: "3.5rem",
    name: "Size 14",
    category: "size",
    equivalent: "56px",
    documentationUrl: "",
  },
  {
    key: "--s-16",
    value: "4rem",
    name: "Size 16",
    category: "size",
    equivalent: "64px",
    documentationUrl: "",
  },
  {
    key: "--s-20",
    value: "5rem",
    name: "Size 20",
    category: "size",
    equivalent: "80px",
    documentationUrl: "",
  },
  {
    key: "--s-24",
    value: "6rem",
    name: "Size 24",
    category: "size",
    equivalent: "96px",
    documentationUrl: "",
  },
  {
    key: "--s-28",
    value: "7rem",
    name: "Size 28",
    category: "size",
    equivalent: "112px",
    documentationUrl: "",
  },
  {
    key: "--s-32",
    value: "8rem",
    name: "Size 32",
    category: "size",
    equivalent: "128px",
    documentationUrl: "",
  },
  {
    key: "--s-36",
    value: "9rem",
    name: "Size 36",
    category: "size",
    equivalent: "144px",
    documentationUrl: "",
  },
  {
    key: "--s-40",
    value: "10rem",
    name: "Size 40",
    category: "size",
    equivalent: "160px",
    documentationUrl: "",
  },
  {
    key: "--s-44",
    value: "11rem",
    name: "Size 44",
    category: "size",
    equivalent: "176px",
    documentationUrl: "",
  },
  {
    key: "--s-48",
    value: "12rem",
    name: "Size 48",
    category: "size",
    equivalent: "192px",
    documentationUrl: "",
  },
  {
    key: "--s-52",
    value: "13rem",
    name: "Size 52",
    category: "size",
    equivalent: "208px",
    documentationUrl: "",
  },
  {
    key: "--s-56",
    value: "14rem",
    name: "Size 56",
    category: "size",
    equivalent: "224px",
    documentationUrl: "",
  },
  {
    key: "--s-60",
    value: "15rem",
    name: "Size 60",
    category: "size",
    equivalent: "240px",
    documentationUrl: "",
  },
  {
    key: "--s-64",
    value: "16rem",
    name: "Size 64",
    category: "size",
    equivalent: "256px",
    documentationUrl: "",
  },
  {
    key: "--s-72",
    value: "18rem",
    name: "Size 72",
    category: "size",
    equivalent: "288px",
    documentationUrl: "",
  },
  {
    key: "--s-80",
    value: "20rem",
    name: "Size 80",
    category: "size",
    equivalent: "320px",
    documentationUrl: "",
  },
  {
    key: "--s-96",
    value: "24rem",
    name: "Size 96",
    category: "size",
    equivalent: "384px",
    documentationUrl: "",
  },
];
