import { Variable } from "../types";

export const borderRadiusVariables: Variable[] = [
  {
    key: "--border-radius-0",
    value: "0px",
    name: "Border Radius 0",
    category: "border-radius",
    equivalent: "0px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-1",
    value: "0.125rem",
    name: "Border Radius 1",
    category: "border-radius",
    equivalent: "2px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-2",
    value: "0.25rem",
    name: "Border Radius 2",
    category: "border-radius",
    equivalent: "4px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-3",
    value: "0.5rem",
    name: "Border Radius 3",
    category: "border-radius",
    equivalent: "8px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-4",
    value: "0.75rem",
    name: "Border Radius 4",
    category: "border-radius",
    equivalent: "12px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-5",
    value: "1rem",
    name: "Border Radius 5",
    category: "border-radius",
    equivalent: "16px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-6",
    value: "1.5rem",
    name: "Border Radius 6",
    category: "border-radius",
    equivalent: "24px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-7",
    value: "2rem",
    name: "Border Radius 7",
    category: "border-radius",
    equivalent: "32px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-8",
    value: "3rem",
    name: "Border Radius 8",
    category: "border-radius",
    equivalent: "48px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-9",
    value: "4rem",
    name: "Border Radius 9",
    category: "border-radius",
    equivalent: "64px",
    documentationUrl: "",
  },
  {
    key: "--border-radius-full",
    value: "9999px",
    name: "Border Radius Full",
    category: "border-radius",
    equivalent: "9999px",
    documentationUrl: "",
  },
];
