import { Variable } from "../types";

export const fontSizeVariables: Variable[] = [
  {
    key: "--font-size-0",
    value: "0.75rem",
    name: "Font Size 0",
    category: "font-size",
    equivalent: "0.75rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-1",
    value: "0.875rem",
    name: "Font Size 1",
    category: "font-size",
    equivalent: "0.875rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-2",
    value: "1rem",
    name: "Font Size 2",
    category: "font-size",
    equivalent: "1rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-3",
    value: "1.125rem",
    name: "Font Size 3",
    category: "font-size",
    equivalent: "1.125rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-4",
    value: "1.25rem",
    name: "Font Size 4",
    category: "font-size",
    equivalent: "1.25rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-5",
    value: "1.5rem",
    name: "Font Size 5",
    category: "font-size",
    equivalent: "1.5rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-6",
    value: "1.875rem",
    name: "Font Size 6",
    category: "font-size",
    equivalent: "1.875rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-7",
    value: "2.25rem",
    name: "Font Size 7",
    category: "font-size",
    equivalent: "2.25rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-8",
    value: "3rem",
    name: "Font Size 8",
    category: "font-size",
    equivalent: "3rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-9",
    value: "3.75rem",
    name: "Font Size 9",
    category: "font-size",
    equivalent: "3.75rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-10",
    value: "4.5rem",
    name: "Font Size 1",
    category: "font-size",
    equivalent: "4.5rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-11",
    value: "6rem",
    name: "Font Size 1",
    category: "font-size",
    equivalent: "6rem",
    documentationUrl: "",
  },
  {
    key: "--font-size-12",
    value: "8rem",
    name: "Font Size 1",
    category: "font-size",
    equivalent: "8rem",
    documentationUrl: "",
  },
];
