import { Variable } from "../types";

export const lineHeightVariables: Variable[] = [
  {
    key: "--line-height-0",
    value: "1rem",
    name: "Line Height 0",
    category: "line-height",
    equivalent: "1rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-1",
    value: "1.25rem",
    name: "Line Height 1",
    category: "line-height",
    equivalent: "1.25rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-2",
    value: "1.5rem",
    name: "Line Height 2",
    category: "line-height",
    equivalent: "1.5rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-3",
    value: "1.75rem",
    name: "Line Height 3",
    category: "line-height",
    equivalent: "1.75rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-4",
    value: "1.75rem",
    name: "Line Height 4",
    category: "line-height",
    equivalent: "1.75rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-5",
    value: "2rem",
    name: "Line Height 5",
    category: "line-height",
    equivalent: "2rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-6",
    value: "2.25rem",
    name: "Line Height 6",
    category: "line-height",
    equivalent: "2.25rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-7",
    value: "2.5rem",
    name: "Line Height 7",
    category: "line-height",
    equivalent: "2.5rem",
    documentationUrl: "",
  },
  {
    key: "--line-height-8",
    value: "1",
    name: "Line Height 8",
    category: "line-height",
    equivalent: "1",
    documentationUrl: "",
  },
  {
    key: "--line-height-9",
    value: "1",
    name: "Line Height 9",
    category: "line-height",
    equivalent: "1",
    documentationUrl: "",
  },
  {
    key: "--line-height-10",
    value: "1",
    name: "Line Height 1",
    category: "line-height",
    equivalent: "1",
    documentationUrl: "",
  },
  {
    key: "--line-height-11",
    value: "1",
    name: "Line Height 1",
    category: "line-height",
    equivalent: "1",
    documentationUrl: "",
  },
  {
    key: "--line-height-12",
    value: "1",
    name: "Line Height 1",
    category: "line-height",
    equivalent: "1",
    documentationUrl: "",
  },
];
