import { Variable } from "../types";

export const sizeVariables: Variable[] = [
  {
    key: "--size-00",
    value: "0px",
    name: "Size 00",
    category: "size",
    equivalent: "0px",
    documentationUrl: "",
  },
  {
    key: "--size-01",
    value: "0.125rem",
    name: "Size 01",
    category: "size",
    equivalent: "2px",
    documentationUrl: "",
  },
  {
    key: "--size-02",
    value: "0.25rem",
    name: "Size 02",
    category: "size",
    equivalent: "4px",
    documentationUrl: "",
  },
  {
    key: "--size-03",
    value: "0.5rem",
    name: "Size 03",
    category: "size",
    equivalent: "8px",
    documentationUrl: "",
  },
  {
    key: "--size-04",
    value: "0.75rem",
    name: "Size 04",
    category: "size",
    equivalent: "12px",
    documentationUrl: "",
  },
  {
    key: "--size-05",
    value: "1rem",
    name: "Size 05",
    category: "size",
    equivalent: "16px",
    documentationUrl: "",
  },
  {
    key: "--size-06",
    value: "1.5rem",
    name: "Size 06",
    category: "size",
    equivalent: "24px",
    documentationUrl: "",
  },
  {
    key: "--size-07",
    value: "2rem",
    name: "Size 07",
    category: "size",
    equivalent: "32px",
    documentationUrl: "",
  },
  {
    key: "--size-08",
    value: "3rem",
    name: "Size 08",
    category: "size",
    equivalent: "48px",
    documentationUrl: "",
  },
  {
    key: "--size-09",
    value: "4rem",
    name: "Size 09",
    category: "size",
    equivalent: "64px",
    documentationUrl: "",
  },
  {
    key: "--size-10",
    value: "6rem",
    name: "Size 10",
    category: "size",
    equivalent: "96px",
    documentationUrl: "",
  },
  {
    key: "--size-11",
    value: "8rem",
    name: "Size 11",
    category: "size",
    equivalent: "128px",
    documentationUrl: "",
  },
  {
    key: "--size-12",
    value: "12rem",
    name: "Size 12",
    category: "size",
    equivalent: "192px",
    documentationUrl: "",
  },
  {
    key: "--size-13",
    value: "16rem",
    name: "Size 13",
    category: "size",
    equivalent: "256px",
    documentationUrl: "",
  },
  {
    key: "--size-14",
    value: "24rem",
    name: "Size 14",
    category: "size",
    equivalent: "384px",
    documentationUrl: "",
  },
  {
    key: "--size-15",
    value: "32rem",
    name: "Size 15",
    category: "size",
    equivalent: "512px",
    documentationUrl: "",
  },
  {
    key: "--size-16",
    value: "48rem",
    name: "Size 16",
    category: "size",
    equivalent: "768px",
    documentationUrl: "",
  },
  {
    key: "--size-17",
    value: "64rem",
    name: "Size 17",
    category: "size",
    equivalent: "1024px",
    documentationUrl: "",
  },
  {
    key: "--size-18",
    value: "90rem",
    name: "Size 18",
    category: "size",
    equivalent: "1440px",
    documentationUrl: "",
  },
];
