import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--blue-50",
    value: "#eff6ff",
    name: "Color Blue 50",
    category: "color",
    equivalent: "#eff6ff",
    documentationUrl: "",
  },
  {
    key: "--blue-100",
    value: "#dbeafe",
    name: "Color Blue 100",
    category: "color",
    equivalent: "#dbeafe",
    documentationUrl: "",
  },
  {
    key: "--blue-200",
    value: "#bfdbfe",
    name: "Color Blue 200",
    category: "color",
    equivalent: "#bfdbfe",
    documentationUrl: "",
  },
  {
    key: "--blue-300",
    value: "#93c5fd",
    name: "Color Blue 300",
    category: "color",
    equivalent: "#93c5fd",
    documentationUrl: "",
  },
  {
    key: "--blue-400",
    value: "#60a5fa",
    name: "Color Blue 400",
    category: "color",
    equivalent: "#60a5fa",
    documentationUrl: "",
  },
  {
    key: "--blue-500",
    value: "#3b82f6",
    name: "Color Blue 500",
    category: "color",
    equivalent: "#3b82f6",
    documentationUrl: "",
  },
  {
    key: "--blue-600",
    value: "#2563eb",
    name: "Color Blue 600",
    category: "color",
    equivalent: "#2563eb",
    documentationUrl: "",
  },
  {
    key: "--blue-700",
    value: "#1d4ed8",
    name: "Color Blue 700",
    category: "color",
    equivalent: "#1d4ed8",
    documentationUrl: "",
  },
  {
    key: "--blue-800",
    value: "#1e40af",
    name: "Color Blue 800",
    category: "color",
    equivalent: "#1e40af",
    documentationUrl: "",
  },
  {
    key: "--blue-900",
    value: "#1e3a8a",
    name: "Color Blue 900",
    category: "color",
    equivalent: "#1e3a8a",
    documentationUrl: "",
  },
];
