import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--emerald-50",
    value: "#ecfdf5",
    name: "Color Emerald 50",
    category: "color",
    equivalent: "#ecfdf5",
    documentationUrl: "",
  },
  {
    key: "--emerald-100",
    value: "#d1fae5",
    name: "Color Emerald 100",
    category: "color",
    equivalent: "#d1fae5",
    documentationUrl: "",
  },
  {
    key: "--emerald-200",
    value: "#a7f3d0",
    name: "Color Emerald 200",
    category: "color",
    equivalent: "#a7f3d0",
    documentationUrl: "",
  },
  {
    key: "--emerald-300",
    value: "#6ee7b7",
    name: "Color Emerald 300",
    category: "color",
    equivalent: "#6ee7b7",
    documentationUrl: "",
  },
  {
    key: "--emerald-400",
    value: "#34d399",
    name: "Color Emerald 400",
    category: "color",
    equivalent: "#34d399",
    documentationUrl: "",
  },
  {
    key: "--emerald-500",
    value: "#10b981",
    name: "Color Emerald 500",
    category: "color",
    equivalent: "#10b981",
    documentationUrl: "",
  },
  {
    key: "--emerald-600",
    value: "#059669",
    name: "Color Emerald 600",
    category: "color",
    equivalent: "#059669",
    documentationUrl: "",
  },
  {
    key: "--emerald-700",
    value: "#047857",
    name: "Color Emerald 700",
    category: "color",
    equivalent: "#047857",
    documentationUrl: "",
  },
  {
    key: "--emerald-800",
    value: "#065f46",
    name: "Color Emerald 800",
    category: "color",
    equivalent: "#065f46",
    documentationUrl: "",
  },
  {
    key: "--emerald-900",
    value: "#064e3b",
    name: "Color Emerald 900",
    category: "color",
    equivalent: "#064e3b",
    documentationUrl: "",
  },
];
