import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--indigo-50",
    value: "#eef2ff",
    name: "Color Indigo 50",
    category: "color",
    equivalent: "#eef2ff",
    documentationUrl: "",
  },
  {
    key: "--indigo-100",
    value: "#e0e7ff",
    name: "Color Indigo 100",
    category: "color",
    equivalent: "#e0e7ff",
    documentationUrl: "",
  },
  {
    key: "--indigo-200",
    value: "#c7d2fe",
    name: "Color Indigo 200",
    category: "color",
    equivalent: "#c7d2fe",
    documentationUrl: "",
  },
  {
    key: "--indigo-300",
    value: "#a5b4fc",
    name: "Color Indigo 300",
    category: "color",
    equivalent: "#a5b4fc",
    documentationUrl: "",
  },
  {
    key: "--indigo-400",
    value: "#818cf8",
    name: "Color Indigo 400",
    category: "color",
    equivalent: "#818cf8",
    documentationUrl: "",
  },
  {
    key: "--indigo-500",
    value: "#6366f1",
    name: "Color Indigo 500",
    category: "color",
    equivalent: "#6366f1",
    documentationUrl: "",
  },
  {
    key: "--indigo-600",
    value: "#4f46e5",
    name: "Color Indigo 600",
    category: "color",
    equivalent: "#4f46e5",
    documentationUrl: "",
  },
  {
    key: "--indigo-700",
    value: "#4338ca",
    name: "Color Indigo 700",
    category: "color",
    equivalent: "#4338ca",
    documentationUrl: "",
  },
  {
    key: "--indigo-800",
    value: "#3730a3",
    name: "Color Indigo 800",
    category: "color",
    equivalent: "#3730a3",
    documentationUrl: "",
  },
  {
    key: "--indigo-900",
    value: "#312e81",
    name: "Color Indigo 900",
    category: "color",
    equivalent: "#312e81",
    documentationUrl: "",
  },
];
