import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--pink-50",
    value: "#fdf2f8",
    name: "Color Pink 50",
    category: "color",
    equivalent: "#fdf2f8",
    documentationUrl: "",
  },
  {
    key: "--pink-100",
    value: "#fce7f3",
    name: "Color Pink 100",
    category: "color",
    equivalent: "#fce7f3",
    documentationUrl: "",
  },
  {
    key: "--pink-200",
    value: "#fbcfe8",
    name: "Color Pink 200",
    category: "color",
    equivalent: "#fbcfe8",
    documentationUrl: "",
  },
  {
    key: "--pink-300",
    value: "#f9a8d4",
    name: "Color Pink 300",
    category: "color",
    equivalent: "#f9a8d4",
    documentationUrl: "",
  },
  {
    key: "--pink-400",
    value: "#f472b6",
    name: "Color Pink 400",
    category: "color",
    equivalent: "#f472b6",
    documentationUrl: "",
  },
  {
    key: "--pink-500",
    value: "#ec4899",
    name: "Color Pink 500",
    category: "color",
    equivalent: "#ec4899",
    documentationUrl: "",
  },
  {
    key: "--pink-600",
    value: "#db2777",
    name: "Color Pink 600",
    category: "color",
    equivalent: "#db2777",
    documentationUrl: "",
  },
  {
    key: "--pink-700",
    value: "#be185d",
    name: "Color Pink 700",
    category: "color",
    equivalent: "#be185d",
    documentationUrl: "",
  },
  {
    key: "--pink-800",
    value: "#9d174d",
    name: "Color Pink 800",
    category: "color",
    equivalent: "#9d174d",
    documentationUrl: "",
  },
  {
    key: "--pink-900",
    value: "#831843",
    name: "Color Pink 900",
    category: "color",
    equivalent: "#831843",
    documentationUrl: "",
  },
];
