import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--amber-50",
    value: "#fffbeb",
    name: "Color Amber 50",
    category: "color",
    equivalent: "#fffbeb",
    documentationUrl: "",
  },
  {
    key: "--amber-100",
    value: "#fef3c7",
    name: "Color Amber 100",
    category: "color",
    equivalent: "#fef3c7",
    documentationUrl: "",
  },
  {
    key: "--amber-200",
    value: "#fde68a",
    name: "Color Amber 200",
    category: "color",
    equivalent: "#fde68a",
    documentationUrl: "",
  },
  {
    key: "--amber-300",
    value: "#fcd34d",
    name: "Color Amber 300",
    category: "color",
    equivalent: "#fcd34d",
    documentationUrl: "",
  },
  {
    key: "--amber-400",
    value: "#fbbf24",
    name: "Color Amber 400",
    category: "color",
    equivalent: "#fbbf24",
    documentationUrl: "",
  },
  {
    key: "--amber-500",
    value: "#f59e0b",
    name: "Color Amber 500",
    category: "color",
    equivalent: "#f59e0b",
    documentationUrl: "",
  },
  {
    key: "--amber-600",
    value: "#d97706",
    name: "Color Amber 600",
    category: "color",
    equivalent: "#d97706",
    documentationUrl: "",
  },
  {
    key: "--amber-700",
    value: "#b45309",
    name: "Color Amber 700",
    category: "color",
    equivalent: "#b45309",
    documentationUrl: "",
  },
  {
    key: "--amber-800",
    value: "#92400e",
    name: "Color Amber 800",
    category: "color",
    equivalent: "#92400e",
    documentationUrl: "",
  },
  {
    key: "--amber-900",
    value: "#78350f",
    name: "Color Amber 900",
    category: "color",
    equivalent: "#78350f",
    documentationUrl: "",
  },
];
