import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--white",
    value: "#ffffff",
    name: "Color White",
    category: "color",
    equivalent: "#ffffff",
    documentationUrl: "",
  },
  {
    key: "--gray-50",
    value: "#f9fafb",
    name: "Color Gray 50",
    category: "color",
    equivalent: "#f9fafb",
    documentationUrl: "",
  },
  {
    key: "--gray-100",
    value: "#f3f4f6",
    name: "Color Gray 100",
    category: "color",
    equivalent: "#f3f4f6",
    documentationUrl: "",
  },
  {
    key: "--gray-200",
    value: "#e5e7eb",
    name: "Color Gray 200",
    category: "color",
    equivalent: "#e5e7eb",
    documentationUrl: "",
  },
  {
    key: "--gray-300",
    value: "#d1d5db",
    name: "Color Gray 300",
    category: "color",
    equivalent: "#d1d5db",
    documentationUrl: "",
  },
  {
    key: "--gray-400",
    value: "#9ca3af",
    name: "Color Gray 400",
    category: "color",
    equivalent: "#9ca3af",
    documentationUrl: "",
  },
  {
    key: "--gray-500",
    value: "#6b7280",
    name: "Color Gray 500",
    category: "color",
    equivalent: "#6b7280",
    documentationUrl: "",
  },
  {
    key: "--gray-600",
    value: "#4b5563",
    name: "Color Gray 600",
    category: "color",
    equivalent: "#4b5563",
    documentationUrl: "",
  },
  {
    key: "--gray-700",
    value: "#374151",
    name: "Color Gray 700",
    category: "color",
    equivalent: "#374151",
    documentationUrl: "",
  },
  {
    key: "--gray-800",
    value: "#1f2937",
    name: "Color Gray 800",
    category: "color",
    equivalent: "#1f2937",
    documentationUrl: "",
  },
  {
    key: "--gray-900",
    value: "#111827",
    name: "Color Gray 900",
    category: "color",
    equivalent: "#111827",
    documentationUrl: "",
  },
  {
    key: "--black",
    value: "#000000",
    name: "Color Black",
    category: "color",
    equivalent: "#000000",
    documentationUrl: "",
  },
];
