import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--green-50",
    value: "#ecfdf5",
    name: "Color Green 50",
    category: "color",
    equivalent: "#ecfdf5",
    documentationUrl: "",
  },
  {
    key: "--green-100",
    value: "#d1fae5",
    name: "Color Green 100",
    category: "color",
    equivalent: "#d1fae5",
    documentationUrl: "",
  },
  {
    key: "--green-200",
    value: "#a7f3d0",
    name: "Color Green 200",
    category: "color",
    equivalent: "#a7f3d0",
    documentationUrl: "",
  },
  {
    key: "--green-300",
    value: "#6ee7b7",
    name: "Color Green 300",
    category: "color",
    equivalent: "#6ee7b7",
    documentationUrl: "",
  },
  {
    key: "--green-400",
    value: "#34d399",
    name: "Color Green 400",
    category: "color",
    equivalent: "#34d399",
    documentationUrl: "",
  },
  {
    key: "--green-500",
    value: "#10b981",
    name: "Color Green 500",
    category: "color",
    equivalent: "#10b981",
    documentationUrl: "",
  },
  {
    key: "--green-600",
    value: "#059669",
    name: "Color Green 600",
    category: "color",
    equivalent: "#059669",
    documentationUrl: "",
  },
  {
    key: "--green-700",
    value: "#047857",
    name: "Color Green 700",
    category: "color",
    equivalent: "#047857",
    documentationUrl: "",
  },
  {
    key: "--green-800",
    value: "#065f46",
    name: "Color Green 800",
    category: "color",
    equivalent: "#065f46",
    documentationUrl: "",
  },
  {
    key: "--green-900",
    value: "#064e3b",
    name: "Color Green 900",
    category: "color",
    equivalent: "#064e3b",
    documentationUrl: "",
  },
];
