import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--purple-50",
    value: "#f5f3ff",
    name: "Color Purple 50",
    category: "color",
    equivalent: "#f5f3ff",
    documentationUrl: "",
  },
  {
    key: "--purple-100",
    value: "#ede9fe",
    name: "Color Purple 100",
    category: "color",
    equivalent: "#ede9fe",
    documentationUrl: "",
  },
  {
    key: "--purple-200",
    value: "#ddd6fe",
    name: "Color Purple 200",
    category: "color",
    equivalent: "#ddd6fe",
    documentationUrl: "",
  },
  {
    key: "--purple-300",
    value: "#c4b5fd",
    name: "Color Purple 300",
    category: "color",
    equivalent: "#c4b5fd",
    documentationUrl: "",
  },
  {
    key: "--purple-400",
    value: "#a78bfa",
    name: "Color Purple 400",
    category: "color",
    equivalent: "#a78bfa",
    documentationUrl: "",
  },
  {
    key: "--purple-500",
    value: "#8b5cf6",
    name: "Color Purple 500",
    category: "color",
    equivalent: "#8b5cf6",
    documentationUrl: "",
  },
  {
    key: "--purple-600",
    value: "#7c3aed",
    name: "Color Purple 600",
    category: "color",
    equivalent: "#7c3aed",
    documentationUrl: "",
  },
  {
    key: "--purple-700",
    value: "#6d28d9",
    name: "Color Purple 700",
    category: "color",
    equivalent: "#6d28d9",
    documentationUrl: "",
  },
  {
    key: "--purple-800",
    value: "#5b21b6",
    name: "Color Purple 800",
    category: "color",
    equivalent: "#5b21b6",
    documentationUrl: "",
  },
  {
    key: "--purple-900",
    value: "#4c1d95",
    name: "Color Purple 900",
    category: "color",
    equivalent: "#4c1d95",
    documentationUrl: "",
  },
];
