import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--red-50",
    value: "#fef2f2",
    name: "Color Red 50",
    category: "color",
    equivalent: "#fef2f2",
    documentationUrl: "",
  },
  {
    key: "--red-100",
    value: "#fee2e2",
    name: "Color Red 100",
    category: "color",
    equivalent: "#fee2e2",
    documentationUrl: "",
  },
  {
    key: "--red-200",
    value: "#fecaca",
    name: "Color Red 200",
    category: "color",
    equivalent: "#fecaca",
    documentationUrl: "",
  },
  {
    key: "--red-300",
    value: "#fca5a5",
    name: "Color Red 300",
    category: "color",
    equivalent: "#fca5a5",
    documentationUrl: "",
  },
  {
    key: "--red-400",
    value: "#f87171",
    name: "Color Red 400",
    category: "color",
    equivalent: "#f87171",
    documentationUrl: "",
  },
  {
    key: "--red-500",
    value: "#ef4444",
    name: "Color Red 500",
    category: "color",
    equivalent: "#ef4444",
    documentationUrl: "",
  },
  {
    key: "--red-600",
    value: "#dc2626",
    name: "Color Red 600",
    category: "color",
    equivalent: "#dc2626",
    documentationUrl: "",
  },
  {
    key: "--red-700",
    value: "#b91c1c",
    name: "Color Red 700",
    category: "color",
    equivalent: "#b91c1c",
    documentationUrl: "",
  },
  {
    key: "--red-800",
    value: "#991b1b",
    name: "Color Red 800",
    category: "color",
    equivalent: "#991b1b",
    documentationUrl: "",
  },
  {
    key: "--red-900",
    value: "#7f1d1d",
    name: "Color Red 900",
    category: "color",
    equivalent: "#7f1d1d",
    documentationUrl: "",
  },
];
