import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--violet-50",
    value: "#f5f3ff",
    name: "Color Violet 50",
    category: "color",
    equivalent: "#f5f3ff",
    documentationUrl: "",
  },
  {
    key: "--violet-100",
    value: "#ede9fe",
    name: "Color Violet 100",
    category: "color",
    equivalent: "#ede9fe",
    documentationUrl: "",
  },
  {
    key: "--violet-200",
    value: "#ddd6fe",
    name: "Color Violet 200",
    category: "color",
    equivalent: "#ddd6fe",
    documentationUrl: "",
  },
  {
    key: "--violet-300",
    value: "#c4b5fd",
    name: "Color Violet 300",
    category: "color",
    equivalent: "#c4b5fd",
    documentationUrl: "",
  },
  {
    key: "--violet-400",
    value: "#a78bfa",
    name: "Color Violet 400",
    category: "color",
    equivalent: "#a78bfa",
    documentationUrl: "",
  },
  {
    key: "--violet-500",
    value: "#8b5cf6",
    name: "Color Violet 500",
    category: "color",
    equivalent: "#8b5cf6",
    documentationUrl: "",
  },
  {
    key: "--violet-600",
    value: "#7c3aed",
    name: "Color Violet 600",
    category: "color",
    equivalent: "#7c3aed",
    documentationUrl: "",
  },
  {
    key: "--violet-700",
    value: "#6d28d9",
    name: "Color Violet 700",
    category: "color",
    equivalent: "#6d28d9",
    documentationUrl: "",
  },
  {
    key: "--violet-800",
    value: "#5b21b6",
    name: "Color Violet 800",
    category: "color",
    equivalent: "#5b21b6",
    documentationUrl: "",
  },
  {
    key: "--violet-900",
    value: "#4c1d95",
    name: "Color Violet 900",
    category: "color",
    equivalent: "#4c1d95",
    documentationUrl: "",
  },
];
