import { Variable } from "../../types";

export const colors: Variable[] = [
  {
    key: "--yellow-50",
    value: "#fffbeb",
    name: "Color Yellow 50",
    category: "color",
    equivalent: "#fffbeb",
    documentationUrl: "",
  },
  {
    key: "--yellow-100",
    value: "#fef3c7",
    name: "Color Yellow 100",
    category: "color",
    equivalent: "#fef3c7",
    documentationUrl: "",
  },
  {
    key: "--yellow-200",
    value: "#fde68a",
    name: "Color Yellow 200",
    category: "color",
    equivalent: "#fde68a",
    documentationUrl: "",
  },
  {
    key: "--yellow-300",
    value: "#fcd34d",
    name: "Color Yellow 300",
    category: "color",
    equivalent: "#fcd34d",
    documentationUrl: "",
  },
  {
    key: "--yellow-400",
    value: "#fbbf24",
    name: "Color Yellow 400",
    category: "color",
    equivalent: "#fbbf24",
    documentationUrl: "",
  },
  {
    key: "--yellow-500",
    value: "#f59e0b",
    name: "Color Yellow 500",
    category: "color",
    equivalent: "#f59e0b",
    documentationUrl: "",
  },
  {
    key: "--yellow-600",
    value: "#d97706",
    name: "Color Yellow 600",
    category: "color",
    equivalent: "#d97706",
    documentationUrl: "",
  },
  {
    key: "--yellow-700",
    value: "#b45309",
    name: "Color Yellow 700",
    category: "color",
    equivalent: "#b45309",
    documentationUrl: "",
  },
  {
    key: "--yellow-800",
    value: "#92400e",
    name: "Color Yellow 800",
    category: "color",
    equivalent: "#92400e",
    documentationUrl: "",
  },
  {
    key: "--yellow-900",
    value: "#78350f",
    name: "Color Yellow 900",
    category: "color",
    equivalent: "#78350f",
    documentationUrl: "",
  },
];
